### ISSUE TITLE
Assigning palette index for maps

### ISSUE THREAD

**Issue by h3xcat** [Optiroc/SuperFamiconv#10]
I wasn't able to figure out, is there a way specify palette index during map generation?

**Comment by Optiroc** [comment]
@edgarasf123 I’m not quite sure I understand what you want to do. To generate a map a palette is always needed and the indices will correspond to the input palette.

**Comment by h3xcat** [comment]
Honestly, I forgot the reason I created this issue. It might not have been related to map generation itself, but the palette generation.

My guess is that I might have posted it before I learned that the indexes themselves were saved within images. Before that, I thought your converter generated the palettes, from finding common RGB values, instead of just extracting them from images.

**Comment by Optiroc** [comment]
It does both actually, with the ‘no-remap` option it uses the palette as is (which requires a palletized/indexed image), else it builds a palette. 

Anyway, I’ll close this issue for now. Sorry about leaving issues on the backburner!
