### ISSUE TITLE
Support Game Boy Color mode

### ISSUE THREAD

**Issue by pinobatch** [Optiroc/SuperFamiconv#11]
Super NES backgrounds have several modes with 2 bits per pixel: all planes of mode 0, the third plane of mode 1, and the second plane of modes 4 and 5. The Game Boy Color tile and palette formats are identical to those of Super NES 2bpp modes, but its tilemap entries arrange bits differently.
```
FEDC BA98 7654 3210  Super NES tilemap
|||| ||++-++++-++++- Character number (max. 0x03FF)
|||+-++------------- Palette
||+----------------- Priority
|+------------------ Flip horizontally
+------------------- Flip vertically

FEDC BA98 7654 3210  Game Boy Color tilemap
|||  +(((-++++-++++- Character number (max. 0x01FF)
|||   +++----------- Palette
||+----------------- Flip horizontally
|+------------------ Flip vertically
+------------------- Priority
```
Two other differences:

- Games are likely to store bits 15-8 and 7-0 in separate arrays because of how VRAM is accessed on that platform.
- Each 4-color subpalette has its own color 0. Instead of (say) palette 3 using colors 0, 13, 14, and 15, it uses colors 12 through 15.

Some Game Boy projects with Super Game Boy support may use SuperFamiconv for the SGB border. If SuperFamiconv also supported GBC tilemaps, this would let games use it for both SGB and GBC assets.

**Comment by Optiroc** [comment]
I've added preliminary Game Boy Color support, but it's thorougly untested as of now.

**Comment by Optiroc** [comment]
GBC mode has been confirmed to work now 👍
