### ISSUE TITLE
Error in deciding to use horizontal or vertical flip ends up in using both

### ISSUE THREAD

**Issue by Molive-0** [Optiroc/SuperFamiconv#13]
If an image is being converted which has a tile which is either the horizontal or vertical flip of a previous tile, the previous tile will be used but it will use both vertical and horizontal flipping, meaning it displays as if no flip has occured at all.

For example, consider the following 16 by 8 pixel image:

![bonus2](https://user-images.githubusercontent.com/23285288/71698996-7eeccc80-2db5-11ea-8a14-eebe5432276b.png)

These two tiles could be encoded as the same tile, just with one flipped either horizontally or vertically.
Superfamiconv encodes the image as such:

![bonus2](https://user-images.githubusercontent.com/23285288/71699045-b8253c80-2db5-11ea-9602-6f5785cc8aa2.png)

The first tile is normal, but the second tile is both flipped horizontally and vertically. This means it looks the same as not flipped at all. In the above case the converter should pick either horizontal or vertical flip but should not pick both.

**Comment by Optiroc** [comment]
Should be fixed as of 08ef68e211a4978357b42a9903b17cfbe888a78c.

**Comment by Optiroc** [comment]
@Molive-0 I really liked this bug, btw, good find!
