### ISSUE TITLE
Auto Pad width on command option

### ISSUE THREAD

**Issue by oziphantom** [Optiroc/SuperFamiconv#18]
Say you have a 256 wide image, that you making into 16x16, so the map needs to be as if it is 512 wide, i.e a screen is still 32 tiles wide. However the tool will make it 16 tiles wide. Having a command line option to out pad the line width to be a "full" line so you can just DMA it and be happy, would be nice. I don't think it should be standard as you may want to use the smaller size to save some ROM.

**Comment by Optiroc** [comment]
This is something I would typically let a pre/post-processing python script do. But maybe it’s a common enough task to include. Will think about it a bit!

Thanks for all the recent feedback 👌

**Comment by Optiroc** [comment]
Hmm, when I thought about it for three seconds... Isn’t your desired output already supported with the `map --map-width` option?

**Comment by Optiroc** [comment]
It requires “advanced mode” usage, that is, splitting up the recipe into `palette`, `tiles` and `map` invocations, where most of the power lies in this tool. 

If I recall correctly this allows for a larger map than the input image, but if not that’s a bug that I’ll fix.

**Comment by oziphantom** [comment]
I was able to solve this with a GUI Frontend in the end.

**Comment by Optiroc** [comment]
@oziphantom Cool, what frontend was that? 

Looking forward to you “big demo” btw! 😉

**Comment by oziphantom** [comment]
just something I threw together in python. Artists use macs, and are allergic to Terminals ;) although to get python gui working on a mac they had to manually chmod things .. can't win
