### ISSUE TITLE
Flag inconsistency

### ISSUE THREAD

**Issue by ARM9** [Optiroc/SuperFamiconv#2]
In shorthand mode the -m flag behaves slightly differently from -t and -p. `-t tiles` and `-p pal` work, but `-m map` does nothing, you have to write `-mmap`.
Run `$ superfamiconv -i freyja.png -t tiles -m map -p pal` and only `tiles` and `pal` are created.

**Comment by Optiroc** [comment]
Oh, thanks for the feedback. I've basically only used longoptions and didn't catch that the generated optstring passed on to `getopt` got completely screwed under certain circumstances. Should be fixed now.
