### ISSUE TITLE
Palette Offsetting

### ISSUE THREAD

**Issue by nikku4211** [Optiroc/SuperFamiconv#23]
I think that offsetting palettes should have been supported from the get go, 

This would make it easier to use multiple PNGs for different layers of graphics in a SNES video mode where palettes are shared, such as:

- Modes 1 and 2, where the first 2 4BPP layers share the same palettes, and where the 2BPP layer shares its 24 colours.
- Modes 3 and 4, where both the 8BPP layer and the other layer share colours(24 in the latter, 120 in the former).
- Mode 5, where both layers share 24 colours.
- Any mode with an 8BPP background will have to share 120 of the colours in the 2nd half with sprites.
- Sure, the 8BPP layer can use direct colour instead, not having to share anything, but SuperFamiconv doesn't support direct colour anyway, and that's something requiring its own issue filed.

**Comment by pinobatch** [comment]
In Super Game Boy, palettes 0-3 are reserved for the system software and 4-7 are used for the game's border.
