### ISSUE TITLE
v0.9.3

### ISSUE THREAD

**Issue by ISSOtm** [Optiroc/SuperFamiconv#36]
v0.9.2 is more than one year old, and [lacks some changes made since then](https://github.com/Optiroc/SuperFamiconv/compare/v0.9.2...master). \*n?x users can fairly easily compile from source, but this is more problematic for Windows users, which usually fall back to 0.9.2's pre-built binaries. Would it be possible to make a release so that they benefit from the changes?

**Comment by Rangi42** [comment]
The only new features are specifying a palette base offset, and supporting 1bpp and 8x16 for DMG/CGB; it *has* been a while, but maybe some of the open bug issues could be fixed before another release.

**Comment by mid-kid** [comment]
It's been three years now, and the currently released version has certain bugs such as not being able to use 8bpp mode on GBA. It'd be nice to see the current version tagged, at least.

**Comment by Optiroc** [comment]
I’ll try to get back to this project now, it’s been gathering dust for way too long 😊

**Comment by Optiroc** [comment]
I made a new release just now, and added a GitHub workflow to make the process simple going forward.

**Comment by ISSOtm** [comment]
Thank you!
