### ISSUE TITLE
100% cpu usage infinite loop on Windows

### ISSUE THREAD

**Issue by ARM9** [Optiroc/SuperFamiconv#4]
When starting the program, regardless of argv, it gets stuck in an infinite loop doing nothing but burning cycles.
Has anyone ran this successfully on Windows? Is this a known issue?

I discovered this a while back but I forgot about it, I'll get to debugging it proper later, just posting this as a reminder.

Windows 8.1 x64, tdm-gcc (mingw-w64 5.1.0, I forget threads/exceptions used, probably posix+dwarf)

**Comment by Optiroc** [comment]
Thanks for the heads up – it's an unknown issue until now (Windows is pretty much unknown territory to me at this point)... Maybe it's the getopts-wrapper.

I'll try to get someone (ping @breakin !) to compile and see what's up.

**Comment by ARM9** [comment]
Optimizations seem to be part of the problem, building with -O0 works so I'll use that for now, if I use any higher level it'll crash. Only had a moment to debug, but it dies in an Options::Add call. For anyone building with mingw, replace sys/ioctl.h with winsock.h.

**Comment by Optiroc** [comment]
OK, interesting. I would've assumed that something would trip up in Options::Parse, not Options:Add. I must find a way to debug gcc generated code.

Happy to see that you find the tool somewhat useful, bugs notwithstanding! (:  It would be neat to be able to distribute working binaries for both Mac and Windows at some not too far off point in the future.

**Comment by Optiroc** [comment]
@ARM9 I got around to set up a Windows VM during the weekend and fiddled around a bit with the available toolchains (Visual Studio 2017 seemed like a good choice in theory, but I found it completely incomprehensible).

Using the mingw toolchain in a cygwin environment I think I've produced working Windows binaries. I decided to statically link the runtime library, so the binary came out at 12MB uncompressed... Argument parsing seems to work fine, but I encountered crashes with huge input images (like a full mode 7 background). Maybe you need to set a larger stack size manually?

Anyway, here's [a binary](https://drive.google.com/file/d/0Bzqgcmx07tCLM2taV1B3Q0xEWVU/view?usp=sharing)! I believe it will only run on x64 Windows. I should look into how to build x86 binaries too, but ran out of patience with Windows for the time being... (:

**Comment by Optiroc** [comment]
I should probably give Visual Studio another shot. For one I good use the easier debugging environment, and I don't feel entirely comfortable with the unnecessary overhead of the mingw libraries.

**Comment by Optiroc** [comment]
I experimented a bit more with the cygwin/mingw setup, and together with Undisbelievers libstdc++ fix the binary seems to work with everything I've thrown at it in my Windows 7 x64 VM.

If anyone who's interested in a pre-built windows binary happens to read this, please check out the [v0.3 release](https://github.com/Optiroc/SuperFamiconv/releases/tag/v0.3)!

**Comment by ARM9** [comment]
That's great, I haven't gotten around to testing your binaries yet but I believe it, stoked for you dude. If you're going to switch to VC++ you'll want to adopt cmake or provide a visual studio solution in addition to the gnu makefile (.vsproj/.sln or whatever).
Are you building with optimizations for Windows?

**Comment by Optiroc** [comment]
The current Windows build is made on cygwin/mingw32-gcc with libstdc++ statically linked, so the filesize is rather enormous but at least it seems to work fine now (at least on my stock Windows 7 x64 install in a normal cmd.exe session). It's built with optimization level -O3 but no LTO.

I should probably take a stab at building with a CMake/VC++ setup.

**Comment by Optiroc** [comment]
I gave VS2017 and CMake on Windows 7 another shot, but the amount of grief that combination of software gives me is just too much... :D  The `CMakeList.txt` I whipped together generates builds just fine on OSX, but got me into a rabbit hole of errors and missing dll's on Windows. 

CMakeLists.txt
```
cmake_minimum_required (VERSION 3.6)
project (superfamiconv)

set(CMAKE_CXX_STANDARD 11)
add_definitions(-DSFC_MONOLITH)
include_directories(include)

set(SOURCES include/LodePNG/lodepng.cpp src/superfamiconv.cpp src/sfc_palette.cpp src/sfc_tiles.cpp src/sfc_map.cpp src/Image.cpp src/Map.cpp src/Palette.cpp src/Tiles.cpp)

add_executable(superfamiconv ${SOURCES})
```

**Comment by ARM9** [comment]
This problem seems to have been resolved, I was unable to reproduce the behaviour on Windows 8.1 with the latest commit.

**Comment by Optiroc** [comment]
Great! I'll check out your PR later tonight!
