### ISSUE TITLE
Wrong map results when PNG has an index marked as transparent

### ISSUE THREAD

**Issue by clbr** [Optiroc/SuperFamiconv#7]
Given a source PNG, 8-bit, where one index is marked as transparent, superfamiconv's map fails to create a correct map. The tiles and palette commands work properly, but the map is missing all tiles that contain that transparent color.

You can create such an image in mtpaint:
- open an 8-bit PNG
- preferences -> files -> set transparency index to 0
- save

**Comment by clbr** [comment]
Actually, the palette command fails too. It sets the transparent color to black, which is obviously wrong.

**Comment by Optiroc** [comment]
Some transparency/color_zero issues should be fixed as of https://github.com/Optiroc/SuperFamiconv/commit/7548126b97351454311066a330776113b5ecc37f.

**Comment by Optiroc** [comment]
I believe these issues should be fixed now. No doubt there are new issues though, since I've refactored the program a lot the last few days. 😉
