### ISSUE TITLE
Wrong map results when two colors are the same

### ISSUE THREAD

**Issue by clbr** [Optiroc/SuperFamiconv#8]
When a palette had two same colors, the map was wrong, it missed some tiles. When I merged the colors, the result became correct.

**Comment by Optiroc** [comment]
Thanks for these reports! It's about time I took a look at the issues you've found now (preferably by finding myself a new project that needs the tool!). Also, I should probably add a test suite...

**Comment by Optiroc** [comment]
@clbr I’m returning to this project for some well needed maintenance. Can you provide example input that exhibits this bug?

**Comment by Optiroc** [comment]
Likely fixed (but I don't have test data to know definitely).
