### ISSUE TITLE
Wrong map results with an 8-bit PNG

### ISSUE THREAD

**Issue by clbr** [Optiroc/SuperFamiconv#9]
This one may be harder to test for you than the others, since I can't share the test image.

Using an 8-bit source PNG (for mode 3, over 16 colors), the map subcommand misses some tiles.
superfamiconv map -v  -B8  --in-image $1 --in-palette $1.palette --in-tiles $1.tiles --out-data $1.map

The image does not have identical colors or a transparent index.

**Comment by clbr** [comment]
Looking at the dumps in hexdump, the missing tiles are not flipped in any way, so I wonder why it misses those. At least missing flipped tiles would be easy to figure out.

**Comment by Optiroc** [comment]
@clbr Interesting. Yeah, I would need example input to debug this.
